#!/bin/bash

inputfile=$(tempfile)
outputfile=$(tempfile)

watch() {
    tail -f $outputfile
    # while [ -e $outputfile ]; do
    # 	output=`cat $outputfile`
    # 	if [ ! -z "$output" ]; then
    # 	    cat $outputfile
    # 	    echo -n > $outputfile
    # 	fi
    # done
}

watch &
IFS=
emacsclient -s "org-ikiwiki-compiler" --eval "(org-ikiwiki-compile \"$inputfile\" \"$outputfile\")" -a "emacs --daemon --eval \"(progn (setq server-name \\"org-ikiwiki-compiler\\") (server-start) (org-ikiwiki-compile \\"$inputfile\\" \\"$outputfile\\"))\"" &
while read -r line; do
    echo -E "$line" >> $inputfile
    echo -E "$line" > /dev/stderr
done

rm $inputfile
rm $outputfile
