#!/bin/bash

inputfile=$(tempfile)
outputfile=$(tempfile)

watch() {
    tail --follow=name $outputfile
}

watch &
IFS=
emacsclient -s "org-ikiwiki-compiler" --eval "(org-ikiwiki-compile \"$inputfile\" \"$outputfile\")" -a "emacs --daemon --eval \"(progn (setq server-name \\"org-ikiwiki-compiler\\") (server-start) (org-ikiwiki-compile \\"$inputfile\\" \\"$outputfile\\"))\"" &
while read -r line; do
    echo -E "$line" >> $inputfile
done

rm $inputfile
rm $outputfile
